export const ROUTES = {
  ROOT: '/',
  LOGIN: '/login',
  LOGOUT: '/logout',
  DASHBOARD: '/dashboard',
  DASHBOARD_CUSTOMERS: '/dashboard/customers',
  DASHBOARD_CUSTOMERS_NEW: '/dashboard/customers/new',
  DASHBOARD_SUBJECTS: '/dashboard/subjects',
  DASHBOARD_SUBJECTS_NEW: '/dashboard/subjects/new',
  DASHBOARD_SUBJECTS_DETAIL: (id: string) => `/dashboard/subjects/${id}`,
  DASHBOARD_SUBJECTS_EDIT: (id: string) => `/dashboard/subjects/${id}/edit`,
  DASHBOARD_ATTENDANCE: '/dashboard/attendance',
  DASHBOARD_SERVICE_CATEGORIES: '/dashboard/service/categories',
  DASHBOARD_SERVICE_BRANDS: '/dashboard/service/brands',
  DASHBOARD_SERVICE_BRAND_DETAIL: (id: string) => `/dashboard/service/brands/${id}`,
  DASHBOARD_SERVICE_DEALERS: '/dashboard/service/dealers',
  DASHBOARD_SERVICE_DEALER_DETAIL: (id: string) => `/dashboard/service/dealers/${id}`, 
  DASHBOARD_INVENTORY: '/dashboard/inventory',
  DASHBOARD_INVENTORY_CATEGORIES: '/dashboard/inventory/categories',
  DASHBOARD_INVENTORY_PRODUCT_TYPES: '/dashboard/inventory/product-types',
  DASHBOARD_INVENTORY_PRODUCTS: '/dashboard/inventory/products',
  DASHBOARD_INVENTORY_PRODUCTS_NEW: '/dashboard/inventory/products/new',
  DASHBOARD_INVENTORY_PRODUCT_EDIT: (id: string) => `/dashboard/inventory/products/${id}/edit`,
  DASHBOARD_INVENTORY_STOCK: '/dashboard/inventory/stock',
  DASHBOARD_INVENTORY_STOCK_NEW: '/dashboard/inventory/stock/new',
  DASHBOARD_INVENTORY_STOCK_BALANCE: '/dashboard/inventory/stock-balance',
  DASHBOARD_TEAM: '/dashboard/team',
  DASHBOARD_TEAM_DETAIL: (id: string) => `/dashboard/team/${id}`,
  DASHBOARD_TECHNICIAN: '/dashboard',
  DASHBOARD_DIGITAL_BAG: '/dashboard/digital-bag',
  DASHBOARD_DIGITAL_BAG_DETAIL: (sessionId: string) => `/dashboard/digital-bag/${sessionId}`,
  DASHBOARD_DIGITAL_BAG_HISTORY: '/dashboard/digital-bag/history',
  DASHBOARD_PAYOUTS: '/dashboard/payouts',
  DASHBOARD_MY_BAG: '/dashboard/my-bag',
  DASHBOARD_LEADERBOARD: '/dashboard/leaderboard',
  DASHBOARD_DUE_PAYMENTS: '/dashboard/due-payments',
  DASHBOARD_COUPONS: '/dashboard/coupons',
  DASHBOARD_PAYOUT_DETAIL: (technicianId: string) => `/dashboard/payouts/${technicianId}`,
  // Reports routes
  DASHBOARD_REPORTS: '/dashboard/reports',
  DASHBOARD_REPORTS_REVENUE: '/dashboard/reports/revenue',
  DASHBOARD_REPORTS_TECHNICIANS: '/dashboard/reports/technicians',
  DASHBOARD_REPORTS_SERVICES: '/dashboard/reports/services',
  DASHBOARD_REPORTS_INVENTORY: '/dashboard/reports/inventory',
  DASHBOARD_REPORTS_CUSTOMERS: '/dashboard/reports/customers',
  DASHBOARD_REPORTS_FINANCIAL: '/dashboard/reports/financial',
  // Settings routes
  DASHBOARD_SETTINGS: '/dashboard/settings',
  DASHBOARD_SETTINGS_PROFILE: '/dashboard/settings/profile',
  DASHBOARD_SETTINGS_COMPANY: '/dashboard/settings/company',
  DASHBOARD_SETTINGS_SYSTEM: '/dashboard/settings/system',
  // AMC routes
  DASHBOARD_AMC: '/dashboard/amc',
  DASHBOARD_AMC_NEW: '/dashboard/amc/new',
  DASHBOARD_AMC_DETAIL: (id: string) => `/dashboard/amc/${id}`,
  DASHBOARD_AMC_RENEW: (id: string) => `/dashboard/amc/${id}/renew`,
} as const;
